title: "毒舌D子ブログ"
description: "生成AI 一次情報を参考にするブログ"
lang: ja

# 公開URL設定（プロジェクトサイト）
baseurl: "/blog"
url: "https://orange-lemon-22.github.io"

# 著者情報（必要最低限）
author:
  name: "毒舌D子"
  bio: "生成AIニュースお届け"

# サイト共通アイコン（記事で icon が未指定のときにも使える）
avatar: "/assets/images/icon.png"

# ビルド設定
markdown: kramdown
permalink: /:year/:month/:day/:title/
theme: null

# プラグイン
plugins:
  - jekyll-feed
  - jekyll-sitemap

# TimeZone
timezone: Asia/Tokyo